config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root :to => "home#index"

  resources :accounts
  resources :transactions
  namespace :api, defaults: { format: :json } do
    resources :users, only: [] do
      member do
        get :transactions
        post :transactions, to: 'users#create_transaction'
      end
    end
  end
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
  has_many :transactions, dependent: :destroy

  validates :name, presence: true
  validates :bank, presence: true, inclusion: { in: ['VCB', 'VIB', 'ACB']}
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :account

  validates :amount, presence: true, numericality: true
  validates :transaction_type, presence: true, inclusion: { in: ['withdraw', 'deposit']}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :accounts, dependent: :destroy
  has_many :transactions, through: :accounts
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  def index
    @accounts = current_user.accounts
  end

  def show
  end

  def new
    @account = Account.new
  end

  def create
    @account = current_user.accounts.new(account_params)

    respond_to do |format|
      if @account.save
        format.html { redirect_to accounts_path, notice: 'Account was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @account.update(account_params)
        format.html { redirect_to accounts_path, notice: 'Account was successfully created.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @account.destroy

    respond_to do |format|
      format.html { redirect_to accounts_path, notice: 'Account was successfully created.' }
    end
  end

  private

  def account_params
    params.require(:account).permit(:name, :bank)
  end

  def set_account
    @account = Account.find(params[:id])
  end
end

app/controllers/api/users_controller.rb
class Api::UsersController < ActionController::API
  before_action :set_user, only: [:transactions, :create_transaction]

  def transactions
    render json: @user.transactions, status: :ok, each_serializer: CustomTransactionSerializer
  end

  def create_transaction
    transaction = @user.transactions.new(transaction_params)
    if transaction.save
      render json: transaction.reload, status: :ok, serializer: CustomTransactionSerializer
    else
      render json: {errors: transaction.errors}, status: :unprocessable_entity
    end
  end

  private

  def transaction_params
    {
      account_id: params[:account_id],
      amount: params[:amount],
      transaction_type: params[:transaction_type]
    }
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController

  before_action :authenticate_user!
  before_action :set_transaction, only: [:show, :edit, :update, :destroy]

  def index
    @transactions = current_user.transactions
  end

  def show
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @transaction = current_user.transactions.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @transaction.destroy

    respond_to do |format|
      format.html { redirect_to transactions_path, notice: 'Transaction was successfully created.' }
    end
  end

  private

  def transaction_params
    params.require(:transaction).permit(:amount, :transaction_type, :account_id)
  end

  def set_transaction
    @transaction = Transaction.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |form| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :bank %><br>
    <%= form.select :bank, [["VCB", "VCB"], ["ACB", "ACB"], ["VIB", "VIB"]] %>
  </p>

  <p>
    <%= link_to "Cancel", accounts_path, class: 'btn btn-secondary' %>
    <%= form.submit flag , class: "btn btn-primary" %>
  </p>
<% end %>

app/views/accounts/edit.html.erb
<div class="col-md-12">
  <h2>Edit Account</h2>
  <%= render partial: 'form', locals: { flag: 'Update' } %>
  <%= link_to "Home Page", root_path %>
</div>

app/views/accounts/index.html.erb
<div class="col-md-12">

  <h1>Listing Accounts</h1><%= link_to "New Account", new_account_path, :class => "btn btn-primary" %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Name</th>
        <th scope="col">Bank</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @accounts.each do |account| %>
        <tr>
          <td><%= account.name %></td>
          <td><%= account.bank %></td>
          <td><%= link_to "Show", account %></td>
          <td><%= link_to "Edit", edit_account_path(account) %></td>
          <td><%= link_to "Destroy", { action: :destroy, id: account.id }, method: :delete, confirm: "Are you sure?" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Home Page', root_path %>

</div>

app/views/accounts/new.html.erb
<div class="col-md-12">
  <h2>New Account</h2>
  <%= render partial: 'form', locals: { flag: 'Create' } %>
  <%= link_to "Home Page", root_path %>
</div>

app/views/accounts/show.html.erb
 <div class="col-md-12">
  <h2> Detail page </h2>
  <p>Name: <%= @account.name %></p>
  <p>Bank: <%= @account.bank %></p>
  <p><%= link_to "Account Page", accounts_path %></p>
</div>

app/views/home/index.html.erb
<div class="jumbotron">
  <% if user_signed_in? %>
    <h1>Welcome!</h1>
    <p class="lead">
      You have signed in!
    </p>
    <%= link_to "Accounts", accounts_path, :class => "btn btn-primary" %>
    <%= link_to "Transactions", transactions_path, :class => "btn btn-primary" %>
    <br>
    <br>
    <%= link_to "Sign Out", destroy_user_session_path, :class => 'btn btn-large btn-danger' %>
  <% else %>
    <h1>Welcome, new user!</h1>
    <p class="lead">
      You must sign in or sign up before you can access our super sweet,
      top secret content.
    </p>
    <div class="row">
      <div class="col-md-6">
        <%= link_to "Sign In", new_user_session_path, :class => "btn btn-success" %>
      </div>
      <div class="col-md6">
        <%= link_to "Sign Up", new_user_registration_path, :class => "btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsCodingChallenge1535</title>
    <%= stylesheet_link_tag    "application", :media => "all" %>
    <%= javascript_include_tag :application %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="container-fluid">
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |form| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
    <%= form.label :amount %><br>
    <%= form.number_field :amount, min: 0, step: 0.01 %>
  </p>

  <p>
    <%= form.label :transaction_type %><br>
    <%= form.select :transaction_type, [["withdraw", "withdraw"], ["deposit", "deposit"]] %>
  </p>

  <p>
    <%= form.label :account %><br>
    <%= select("transaction", "account_id", Account.all.collect { |p| [ p.name, p.id ] })  %>
  </p>

  <p>
    <%= link_to "Cancel", transactions_path, class: 'btn btn-secondary' %>
    <%= form.submit flag , class: "btn btn-primary" %>
  </p>
<% end %>

app/views/transactions/edit.html.erb
<div class="col-md-12">
  <h2>Edit Transaction</h2>
  <%= render partial: 'form', locals: { flag: 'Update' } %>
  <%= link_to "Home Page", root_path %>
</div>

app/views/transactions/index.html.erb
<div class="col-md-12">

  <h1>Listing Transactions</h1><%= link_to "New Transaction", new_transaction_path, :class => "btn btn-primary" %>

  <table class="table table-striped">
    <thead>
      <tr>
        <th scope="col">Amount</th>
        <th scope="col">Transaction</th>
        <th scope="col">Account Name</th>
        <th scope="col" colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @transactions.each do |item| %>
        <tr>
          <td><%= item.amount %></td>
          <td><%= item.transaction_type %></td>
          <td><%= item.account.name %></td>
          <td><%= link_to "Show", item %></td>
          <td><%= link_to "Edit", edit_transaction_path(item) %></td>
          <td><%= link_to "Destroy", { action: :destroy, id: item.id }, method: :delete, confirm: "Are you sure?" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%= link_to 'Home Page', root_path %>
</div>

app/views/transactions/new.html.erb
<div class="col-md-12">
  <h2>New Transaction</h2>
  <%= render partial: 'form', locals: { flag: 'Create' } %>
  <%= link_to "Home Page", root_path %>
</div>

app/views/transactions/show.html.erb
 <div class="col-md-12">
  <h2> Detail page </h2>
  <p>Name: <%= @transaction.amount %></p>
  <p>Bank: <%= @transaction.transaction_type %></p>
  <p>Account name: <%= @transaction.account.name %></p>
  <p><%= link_to "Transactions Page", transactions_path %></p>
</div>